/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './dependencies/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'palette-red': '#a62a1e',
        'palette-white': '#f7f7f7',
        'palette-black': '#1f1f1f',
        'palette-grey': '#3c3c3c',
        'palette-lite-grey': '#e1e4e7',
        'palette-lite-grey-accent': '#d3d4d8',
        'palette-stone': '#c9c9c9',
        'palette-blue': '#335075',
        'palette-dark-blue': '#38414d',
        'ui-dark-bg': '#212121',
        'ui-btn-bg-active': '#2f2f2f',
        'ui-btn-bg-focus': '#171717',
        'ui-dark-border-color': 'rgba(255, 255, 255, 0.07)',
      },
      fontFamily: {
        'ui-default': [
          '-apple-system-body',
          'ui-sans-serif',
          '-apple-system',
          'system-ui',
          '"Segoe UI"',
          'Helvetica',
          '"Apple Color Emoji"',
          'Arial',
          'sans-serif',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
        ],
        roboto: ['Roboto', 'sans-serif'],
        'open-sans': ['"Open Sans"', 'sans-serif'],
        playfair: ['"Playfair Display"', 'serif'],
      },
    },
    screens: {
      s500: '500px',
      'max-s500': { max: '500px' },
      s768: '768px',
      'max-s768': { max: '768px' },
      s992: '992px',
      'max-s992': { max: '992px' },
      s1200: '1200px',
      'max-s1200': { max: '1200px' },
    },
  },
  plugins: [],
};
